### PR TITLE
Jsonaf

### PR DESCRIPTION
**Pull request by dvmitrv**
Hello!

I've added a `Decoders_jsonaf` module for [janestreet/jsonaf](https://github.com/janestreet/jsonaf).

Regarding tests, I was rather lazy and just took `yojson_basic_suite` and adapted it for `jsonaf`.  I've credited @mattjbray for this, hope it's okay!

### CODE REVIEW

**Comment by mattjbray** [comment]
Looks great! Just need to figure out how to skip the 4.08 build for this package.

**Comment by mattjbray** [comment]
Can you rebase this on master and then add `decoders-jsonaf` to the package matrix: https://github.com/mattjbray/ocaml-decoders/blob/22a7856c1ee406aaf17fe6941fa46f65319677c7/.github/workflows/build.yml#L20-L28

**Comment by mattjbray** [comment]
I'm working on a fix in #52

**Comment by mattjbray** [comment]
Ok #52 is merged, if you rebase again hopefully it'll pass this time 🤞

**Comment by mattjbray** [comment]
Thanks!

**Comment by dvmitrv** [comment]
Thank you for the quick process!

**Pull request merged**
